# SPDX-License-Identifier: GPL-2.0
# Device Tree Makefile for vendor boards
srctree ?= /lib/modules/$(shell uname -r)/build
include $(srctree)/scripts/Makefile.lib

dtbo-y += sun50i-h616-ph-emc2101.dtbo
dtbo-y += sun50i-h616-ph-st7789v.dtbo